version: '3'

volumes:
  kittygram_data:
  static:
  media:

services:
  kittygram_db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - kittygram_db
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media: /media
